# Generated by Django 4.2 on 2024-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutsom_user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
