# Generated by Django 4.2 on 2024-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_cutsom_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutsom_user',
            name='delete_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='delete_user code'),
        ),
    ]
