# Generated by Django 4.2 on 2024-09-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', error_messages={'unique': 'A Group With Such Name Exists!'}, max_length=100, unique=True, verbose_name="group's title")),
                ('picture', models.ImageField(blank=True, null=True, upload_to='groups_images')),
                ('group_type', models.CharField(choices=[('two', 'two'), ('many', 'many')], default='many', max_length=5, verbose_name='type of group chat')),
            ],
            options={
                'verbose_name': 'chat_group',
                'verbose_name_plural': 'chat_groups',
                'db_table': 'chat_groups',
            },
        ),
        migrations.CreateModel(
            name='chat_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('aanoucement', 'aanoucement'), ('message', 'message')], default='message', max_length=15, verbose_name='message_type')),
                ('message', models.CharField(default='', max_length=1000, verbose_name="message's text")),
                ('file', models.FileField(blank=True, null=True, upload_to='group_photos', verbose_name="message's file")),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name="message's date")),
            ],
            options={
                'verbose_name': 'chat_message',
                'verbose_name_plural': 'chat_messages',
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='seen_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups_and_messages.chat_messages', verbose_name='the message')),
            ],
        ),
    ]
